# ---------------------------------------------------------------------------
# Pasta base
# ---------------------------------------------------------------------------
#
# Define a pasta base
# 
base : '/../../'

# ---------------------------------------------------------------------------
# Pasta da aplicaçao
# ---------------------------------------------------------------------------
#
# Define a pasta da aplicação
# 
app : '/../../app'

# ---------------------------------------------------------------------------
# Pasta da public
# ---------------------------------------------------------------------------
#
# Define a pasta visivel para o usuário
# 
public : '/../../public'

# ---------------------------------------------------------------------------
# Pasta de storage
# ---------------------------------------------------------------------------
#
# Define a pasta de storage onde será gravado cache e logs
# 
storage : '/../../app/storage'